export const RouteConst = {
  WeatherRecommend: '/weatherRecommend',
  Main: '/',
  LoginOn: '/login',
  SignUp: '/signup',
  MyPage: '/mypage',
  Community: '/community',
  Write: '/community/write',
  Detail: '/community/:id',
  MUBTI: '/mubti',
  Survey: '/mubti/1',
  Mood: '/mubti/mood',
  Situation: '/mubti/situation',
  Liking: '/mubti/liking',
  Result: '/mubti/result',
  Loading: '/mubti/loading',
  Test: '/test',
  EditProfile: '/mypage/edit',
  Search: '/search',
};
